DROP VIEW IF EXISTS PokemonNameEvolutionsView;
DROP TABLE IF EXISTS Encounters;
DROP TABLE IF EXISTS Gym;
DROP TABLE IF EXISTS PokemartSellsItems;
DROP TABLE IF EXISTS PokemonEvolvesTo;
DROP TABLE IF EXISTS PokemonHasMoves;
DROP TABLE IF EXISTS PokemonHasTypes;
DROP TABLE IF EXISTS Stone;
DROP TABLE IF EXISTS StoneEvolutions;

DROP TABLE IF EXISTS Pokemart;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Moves;
DROP TABLE IF EXISTS Pokemon;
DROP TABLE IF EXISTS Types;